variables:
  GIT_SUBMODULE_STRATEGY: recursive


stages:
  - dependencies
  - modules
  - build
  - deploy

webworker-dependencies:
  stage: dependencies
  image: node:lts
  script:
    - cd SOSML-webworker && npm ci
  artifacts:
    expire_in: 1 day
    paths:
      - SOSML-webworker/node_modules


frontend-dependencies:
  stage: dependencies
  image: node:lts
  script:
    - cd SOSML-frontend/frontend && npm ci
  artifacts:
    expire_in: 1 day
    paths:
      - SOSML-frontend/frontend/node_modules


backend-dependencies:
  stage: dependencies
  image: node:lts
  script:
    - npm ci
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules

build-webworker:
  stage: modules
  image: node:lts
  script:
    - cd SOSML-webworker && npm run dist
  dependencies:
    - webworker-dependencies
  artifacts:
    expire_in: 1 day
    paths:
      - SOSML-webworker/build/webworker.js


build-frontend:
  stage: build
  image: node:lts
  script:
    - cp SOSML-webworker/build/webworker.js SOSML-frontend/frontend/public/webworker.js
    - ./configure.sh
    - cd SOSML-frontend/frontend && npm run build
  dependencies:
    - build-webworker
    - frontend-dependencies
  artifacts:
    expire_in: 2 weeks
    paths:
      - SOSML-frontend/frontend/build/
      - SOSML-frontend/frontend/public/


.deploy-web: &deploy-web
  stage: deploy
  image: udsdepend/gitlab-ssh-deploy
  tags:
    - secret
  dependencies:
    - build-frontend


deploy-web-main:
  <<: *deploy-web
  only:
    - main@sosml/backend
  script:
    - /ssh-deploy.sh './deploy-web.sh main' '~/deploy-cache/web/main' ./deploy-web.sh ./SOSML-frontend/frontend/build/
  environment:
    name: development-web
    url: https://sosml.org/


deploy-web-exp:
  <<: *deploy-web
  only:
    - exp@sosml/backend
  script:
    - /ssh-deploy.sh './deploy-web.sh exp' '~/deploy-cache/web/exp' ./deploy-web.sh ./SOSML-frontend/frontend/build/
  environment:
    name: development-web
    url: https://exp.sosml.org/


deploy-web-dev:
  <<: *deploy-web
  only:
    - dev@sosml/backend
  script:
    - /ssh-deploy.sh './deploy-web.sh dev' '~/deploy-cache/web/dev' ./deploy-web.sh ./SOSML-frontend/frontend/build/
  environment:
    name: development-web
    url: https://dev.sosml.org/


deploy-server:
  stage: deploy
  image: udsdepend/gitlab-ssh-deploy
  tags:
    - secret
  only:
    - main@sosml/backend
  dependencies:
    - backend-dependencies
  script:
    - /ssh-deploy.sh './deploy-server.sh' '~/deploy-cache/server' ./deploy-server.sh ./src config.js ./node_modules
  environment:
    name: production-server
    url: https://pseuCo.com/api/
